# Generated by Django 4.2.6 on 2023-10-04 18:01

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=django_jsonform.models.fields.JSONField(default=""),
            preserve_default=False,
        ),
    ]
