# Generated by Django 4.2.6 on 2023-10-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_order_items_delete_orderitem_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="dealer",
        ),
        migrations.AddField(
            model_name="order",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="core.billbook",
            ),
            preserve_default=False,
        ),
    ]
