# Generated by Django 4.2.6 on 2023-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_order_dealer_order_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("ready", "ready"),
                    ("delivered", "delivered"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
