# Generated by Django 4.2.6 on 2023-10-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='book',
            new_name='bill_book',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('bill_book', 'order_number')},
        ),
    ]
