# Generated by Django 4.2.6 on 2023-10-04 18:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[],
            options={
                "verbose_name": "Dealer",
                "verbose_name_plural": "Dealers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("custom_auth.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
